name: Gen Clash YAML

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次
  workflow_dispatch:    # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your yaml template repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            iKuuu_V2.yaml

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml requests

      - name: Generate clash.yaml
        run: python gen_clash.py

      - name: Commit and push clash.yaml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update clash.yaml from proxy-list"
          file_pattern: "clash.yaml"
